'use client'

import { useEffect, useState, useRef, Suspense, Fragment } from 'react'
import { createClient } from '@/utils/supabase/client'
import { useRouter, useSearchParams } from 'next/navigation'
import { pdf } from '@react-pdf/renderer'
import { DiagnosticoPDF } from '@/app/utils/DiagnosticoPDF'
import TabCliente from './components/TabCliente'
import TabEntregable from './components/TabEntregable'
import TabCuantias from './components/TabCuantias'
import TabImporte from './components/TabImporte'
import TabEscenarios from './components/TabEscenarios'
import TabSalarioMod40 from './components/TabSalarioMod40'
import TabCostoMod40 from './components/TabCostoMod40'
import TabFinanciamiento from './components/TabFinanciamiento'
import TabProyeccion from './components/TabProyeccion'
import { avisoError } from '@/app/utils/avisos'
